/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 * @generated by codegen project: GenerateModuleH.js
 */
#include "RNImagePickerTurbomodule.h"
using namespace rnoh;
using namespace facebook;

static jsi::Value __hostFunction_RNImagePickerTurboModule_launchCamera(jsi::Runtime &rt,
                                                                       react::TurboModule &turboModule,
                                                                       const jsi::Value *args, size_t count) {
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "launchCamera", args, count);
}
static jsi::Value __hostFunction_RNImagePickerTurboModule_launchImageLibrary(jsi::Runtime &rt,
                                                                             react::TurboModule &turboModule,
                                                                             const jsi::Value *args, size_t count) {
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "launchImageLibrary", args, count);
}

RNImagePickerTurboModule::RNImagePickerTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
    : ArkTSTurboModule(ctx, name) {
    methodMap_["launchCamera"] = MethodMetadata{0, __hostFunction_RNImagePickerTurboModule_launchCamera};
    methodMap_["launchImageLibrary"] = MethodMetadata{0, __hostFunction_RNImagePickerTurboModule_launchImageLibrary};
}